### ISSUE TITLE
FE] 사용자 내보내기 및 초대 로직 개선

### ISSUE THREAD

**Issue by yesolyo** [yesolyo/trecord-fe#17]
## ☑️ 진행할 작업

- 사용자 내보내기 및 초대 로직 개선과  square btn 로직 통일성있게 개선

## 📝 TODO

- [ ] : 사용자 초대했을 때, 초대하는 사용자만 리스트에 표시되게 개선
- [ ] : 초대하는 사용자를 클릭했을 때 초대되고, 리스트에서 표시 안 되게 개선
- [ ] : 초대 링크 공유했을 때 수정안되게 개선
- [ ] : square btn 로직 통일성있게 개선
