### ISSUE TITLE
[FE] 초대하기 기능 개선

### ISSUE THREAD

**Issue by yesolyo** [yesolyo/trecord-fe#25]
## ☑️ 진행할 작업

- 피드 등록, 기록 등록 부분에서 기존 초대하기 기능이 오류가 있어서 초대하기 기능을 개선한다.
- 초대 모달을 클릭 후 닉네임을 입력하다가 다시 나갔다가 들어오면 닉네임이 없어지게 설정한다.

## 📝 TODO

1. 피드 등록 초대하기 기능 개선(새등록, 수정)

- [ ] : 같이간 친구 이름 클릭 시 바로 초대 적용
- [ ] : 초대가 적용된 이름 클릭 시 내보내기 기능 적용
 
2. 기록등록 초대하기 기능 개선(새등록,수정)

- [ ] : 같이간 친구 이름 클릭 시 바로 초대 적용
- [ ] : 초대가 적용된 이름 클릭 시 내보내기 기능 적용
- [ ] : 초대 모달에서 초대를 안하고 모달을 닫았다가 다시 들어가면 적어놓은 닉네임이 없게 설정
